### ISSUE TITLE
taylor binary does not work for me

### ISSUE THREAD

**Issue by rubyFeedback** [HellRok/Taylor#1]
./taylor 
    ./taylor: /usr/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./taylor)

I am stuck on glibc 2.28 right now. Anyway, this is just to let you know that this may not work for
everyone right now (damn glibc versions...)

**Comment by HellRok** [comment]
I'm curious what distro you're on. I have it running on Debian Bullseye, Ubuntu 20.04, and Fedora 32. I know there were issues with glibc on Debian Buster.

I'm afraid the only real advice I can give is try to upgrade your distro if you can, otherwise you'll need to compile it yourself which I'm about to write up some instructions for in the README

**Comment by HellRok** [comment]
Alright! The linux binaries are now compiled using Debian oldstable so this will now work with glibc 2.28!
