### ISSUE TITLE
Why MRuby instead of CRuby?

### ISSUE THREAD

**Issue by Nathan-MV** [HellRok/Taylor#21]
CRuby is generally faster but causes more overhead than MRuby, so was it decided to use MRuby instead?

**Comment by HellRok** [comment]
The main reason I chose to use MRuby is because I wanted something that could be compiled into a single executable file for ease of distribution. I also knew that MRuby was more portable than CRuby (with Android and WASM being my primary concerns)

Another reason is because you can keep your source code safe while distributing your game by using `mrbc` which to the best of my knowledge is not able to be decompiled (at least in any meaningful way).

I've not built a native extension based gem before but it feels like Taylor could be refactored to make it a possibility, but I don't have any interest in doing that myself.
